### ISSUE TITLE
Support for misc NFC cards

### ISSUE THREAD

**Issue by petterroea** [dotkom/mysterious-powerking-conspiracy#11]
I don't usually carry my NTNU card as my phone card holder only fits 3 cards(and currently contains 6 cards). Because of this, i am requesting that you can, while logged in, assign other NFC cards to your user account. 

The process of assigning a card to you for the first time:

 * Scan your NTNU card
 * Press a fancy button
 * Scan your other card

After this, the system would log in as me when i scan the other card. 

You should also be able to de-register the card, should you lose it or sell it or for some other reason not want it to be able to unlock your powerking-funds.

Possible security restrictions:

 * Minimum UID size(dont use a cheap 4-byte uid card!)
 * Requiring the NTNU card in order to assign more secondary cards(or, management of secondary cards can only be done using your NTNU card)

**Comment by FredrikAugust** [comment]
Afternoon good sir. This has also been brought up quite some times, and I do believe I have a solution for it. Due to some other issues that have been submitted, I'll have to create a separate back-end for nibble anyways, so might as well add this as a feature. 

Should be any harder than checking all incoming cards to see if they're registered as a _proxy_, and if they are, submit the request to OW with the real NTNU card.

**Comment by Aborysa** [comment]
Thanks for the feedback, sadly we don't see this happen in the close future.
